@wallet = 0xYourWalletAddress000000000000000000000000
@signature = 0xSignatureFromWalletSignMessage
@baseUrl = http://127.0.0.1:8888
@timestamp = {{$timestamp}}
@roundId = 1
@taskName = daily_checkin

###
### 用户登录，换取 JWT
### @name login
POST {{baseUrl}}/api/airdrop/v1/auth/login
Content-Type: application/json

{
  "wallet": "{{wallet}}",
  "signature": "{{signature}}",
  "timestamp": {{timestamp}}
}

{{
  $global.accessToken=response.parsedBody.data.accessToken;
}}

###
### 查询当前用户积分，需要 Bearer Token
GET {{baseUrl}}/api/airdrop/v1/me/points
Authorization: Bearer {{$global.accessToken}}

###
### 查询当前用户空投领取证明，需要 Bearer Token
GET {{baseUrl}}/api/airdrop/v1/airdrop/me/proof?roundId=12
Authorization: Bearer {{$global.accessToken}}

###
### 查询当前空投轮次（管理员 JWT） 10
GET {{baseUrl}}/api/airdrop/v1/admin/airdrop/round?roundId=12
Authorization: Bearer {{$global.accessToken}}

###
### 启动新一轮空投（管理员 JWT）
POST {{baseUrl}}/api/airdrop/v1/admin/airdrop/start
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json

{
  "roundName": "season-4",
  "tokenAddress": "0x4356a7628f97612dd8fac80b1f8354962d12123c",
  "claimDeadline": 1796047259
}
