// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

import "math/big"

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type ClaimProofData struct {
	RoundId int64    `json:"roundId"`
	Wallet  string   `json:"wallet"`
	Amount  *big.Int `json:"amount"`
	Proof   []string `json:"proof"`
}

type ClaimProofRequest struct {
	RoundId int64 `form:"roundId"`
}

type ClaimProofResponse struct {
	BaseResp
	Data ClaimProofData `json:"data"`
}

type LoginData struct {
	AccessToken string `json:"accessToken"`
	ExpiresAt   int64  `json:"expiresAt"`
	LoginDays   int64  `json:"loginDays"`
	Points      int64  `json:"points"`
}

type LoginRequest struct {
	Wallet    string `json:"wallet"`
	Signature string `json:"signature"`
	Timestamp int64  `json:"timestamp"`
}

type LoginResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type PointsData struct {
	Wallet      string `json:"wallet"`
	Available   int64  `json:"available"`
	Frozen      int64  `json:"frozen"`
	LatestRound int64  `json:"latestRound"`
	LoginStreak int64  `json:"loginStreak"`
}

type PointsResponse struct {
	BaseResp
	Data PointsData `json:"data"`
}

type RoundInfoData struct {
	CurrentRoundId int64  `json:"currentRoundId"`
	RoundName      string `json:"roundName"`
	ClaimDeadline  int64  `json:"claimDeadline"`
	MerkleRoot     string `json:"merkleRoot"`
	TokenAddress   string `json:"tokenAddress"`
	TotalPoints    int64  `json:"totalPoints"`
}

type RoundInfoRequest struct {
	RoundId uint64 `form:"roundId"`
}

type RoundInfoResponse struct {
	BaseResp
	Data RoundInfoData `json:"data"`
}

type StartRoundRequest struct {
	RoundName     string `json:"roundName"`
	TokenAddress  string `json:"tokenAddress"`
	ClaimDeadline int64  `json:"claimDeadline"`
}

type SubmitTaskData struct {
	Points      int64 `json:"points"`
	TotalPoints int64 `json:"totalPoints"`
}

type SubmitTaskRequest struct {
	Wallet      string `json:"wallet"`
	TaskCode    string `json:"taskCode"`
	ProveParams string `json:"proveParams"`
}

type SubmitTaskResponse struct {
	BaseResp
	Data SubmitTaskData `json:"data"`
}
